### PR TITLE
Refactor getRecipes in preparation for Forge's changes to getValues

### PR DESCRIPTION
**Pull request by josephcsible**

### CODE REVIEW

**Comment by josephcsible** [comment]
The change in question is that they're going to start giving you a `Collection<IRecipe>` instead of a `List<IRecipe>`. After I made this, I noticed that this now makes an independent list rather than a view that stays up-to-date. If the latter is important, then we'd need to change `IRecipeHandler#getRecipes()` to return a `Collection<RecipeDefinition>` instead of a `List<RecipeDefinition>` (which would be a breaking change), but then we could just use `Collections2.transform` in place of `Lists.transform`.

**Comment by rubensworks** [comment]
AFAIK, `stream().map()` doesn't create a lazy-transformed list, so this change will introduce a big performance issue when only subsets of the given list are needed.

I haven't looked into `Collections2.transform` yet, but that sounds good to me at the moment. The recipe capability is not included in public releases anyways, so breaking changes are fine.

**Comment by josephcsible** [comment]
It looks like Collections2.transform is exactly what we want then, if breaking changes are okay. I'll change this PR to do that tonight.

**Comment by josephcsible** [comment]
This now depends on CyclopsMC/CommonCapabilitiesAPI#5.

**Comment by rubensworks** [comment]
@josephcsible https://github.com/CyclopsMC/CommonCapabilitiesAPI/pull/5 has been merged, could you update the submodule in this PR as well?

**Comment by josephcsible** [comment]
Done.

**Pull request merged**
